// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LeaderboardRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	Mode     string `form:"mode"`
}

type LeaderboardEntry struct {
	MemberId string `json:"member_id"`
	Rank     int64  `json:"rank"`
	Score    int64  `json:"score"`
	Penalty  int64  `json:"penalty"`
	Detail   string `json:"detail"`
}

type PageInfo struct {
	Page     int   `json:"page"`
	PageSize int   `json:"page_size"`
	Total    int64 `json:"total"`
}

type LeaderboardPayload struct {
	Items   []LeaderboardEntry `json:"items"`
	Page    PageInfo           `json:"page"`
	Version string             `json:"version"`
}

type LeaderboardResponse struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Data    LeaderboardPayload `json:"data"`
	Details map[string]string  `json:"details,omitempty"`
	TraceId string             `json:"trace_id,omitempty"`
}
