// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemManifestFieldNames          = builder.RawFieldNames(&ProblemManifest{})
	problemManifestRows                = strings.Join(problemManifestFieldNames, ",")
	problemManifestRowsExpectAutoSet   = strings.Join(stringx.Remove(problemManifestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemManifestRowsWithPlaceHolder = strings.Join(stringx.Remove(problemManifestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemManifestModel interface {
		Insert(ctx context.Context, data *ProblemManifest) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProblemManifest, error)
		FindOneByProblemVersionId(ctx context.Context, problemVersionId int64) (*ProblemManifest, error)
		Update(ctx context.Context, data *ProblemManifest) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProblemManifestModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProblemManifest struct {
		Id               int64  `db:"id"`
		ProblemVersionId int64  `db:"problem_version_id"`
		ManifestJson     string `db:"manifest_json"`
	}
)

func newProblemManifestModel(conn sqlx.SqlConn) *defaultProblemManifestModel {
	return &defaultProblemManifestModel{
		conn:  conn,
		table: "`problem_manifest`",
	}
}

func (m *defaultProblemManifestModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemManifestModel) FindOne(ctx context.Context, id int64) (*ProblemManifest, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemManifestRows, m.table)
	var resp ProblemManifest
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemManifestModel) FindOneByProblemVersionId(ctx context.Context, problemVersionId int64) (*ProblemManifest, error) {
	var resp ProblemManifest
	query := fmt.Sprintf("select %s from %s where `problem_version_id` = ? limit 1", problemManifestRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, problemVersionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemManifestModel) Insert(ctx context.Context, data *ProblemManifest) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, problemManifestRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProblemVersionId, data.ManifestJson)
	return ret, err
}

func (m *defaultProblemManifestModel) Update(ctx context.Context, newData *ProblemManifest) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemManifestRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProblemVersionId, newData.ManifestJson, newData.Id)
	return err
}

func (m *defaultProblemManifestModel) tableName() string {
	return m.table
}
