// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemDataPackFieldNames          = builder.RawFieldNames(&ProblemDataPack{})
	problemDataPackRows                = strings.Join(problemDataPackFieldNames, ",")
	problemDataPackRowsExpectAutoSet   = strings.Join(stringx.Remove(problemDataPackFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemDataPackRowsWithPlaceHolder = strings.Join(stringx.Remove(problemDataPackFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemDataPackModel interface {
		Insert(ctx context.Context, data *ProblemDataPack) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProblemDataPack, error)
		Update(ctx context.Context, data *ProblemDataPack) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProblemDataPackModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProblemDataPack struct {
		Id               int64     `db:"id"`
		ProblemVersionId int64     `db:"problem_version_id"`
		ObjectKey        string    `db:"object_key"`
		SizeBytes        int64     `db:"size_bytes"`
		Md5              string    `db:"md5"`
		Sha256           string    `db:"sha256"`
		CreatedAt        time.Time `db:"created_at"`
	}
)

func newProblemDataPackModel(conn sqlx.SqlConn) *defaultProblemDataPackModel {
	return &defaultProblemDataPackModel{
		conn:  conn,
		table: "`problem_data_pack`",
	}
}

func (m *defaultProblemDataPackModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemDataPackModel) FindOne(ctx context.Context, id int64) (*ProblemDataPack, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemDataPackRows, m.table)
	var resp ProblemDataPack
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemDataPackModel) Insert(ctx context.Context, data *ProblemDataPack) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, problemDataPackRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProblemVersionId, data.ObjectKey, data.SizeBytes, data.Md5, data.Sha256)
	return ret, err
}

func (m *defaultProblemDataPackModel) Update(ctx context.Context, data *ProblemDataPack) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemDataPackRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProblemVersionId, data.ObjectKey, data.SizeBytes, data.Md5, data.Sha256, data.Id)
	return err
}

func (m *defaultProblemDataPackModel) tableName() string {
	return m.table
}
