// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemVersionSeqFieldNames          = builder.RawFieldNames(&ProblemVersionSeq{})
	problemVersionSeqRows                = strings.Join(problemVersionSeqFieldNames, ",")
	problemVersionSeqRowsExpectAutoSet   = strings.Join(stringx.Remove(problemVersionSeqFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemVersionSeqRowsWithPlaceHolder = strings.Join(stringx.Remove(problemVersionSeqFieldNames, "`problem_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemVersionSeqModel interface {
		Insert(ctx context.Context, data *ProblemVersionSeq) (sql.Result, error)
		FindOne(ctx context.Context, problemId int64) (*ProblemVersionSeq, error)
		Update(ctx context.Context, data *ProblemVersionSeq) error
		Delete(ctx context.Context, problemId int64) error
	}

	defaultProblemVersionSeqModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProblemVersionSeq struct {
		ProblemId   int64 `db:"problem_id"`
		NextVersion int64 `db:"next_version"`
	}
)

func newProblemVersionSeqModel(conn sqlx.SqlConn) *defaultProblemVersionSeqModel {
	return &defaultProblemVersionSeqModel{
		conn:  conn,
		table: "`problem_version_seq`",
	}
}

func (m *defaultProblemVersionSeqModel) Delete(ctx context.Context, problemId int64) error {
	query := fmt.Sprintf("delete from %s where `problem_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, problemId)
	return err
}

func (m *defaultProblemVersionSeqModel) FindOne(ctx context.Context, problemId int64) (*ProblemVersionSeq, error) {
	query := fmt.Sprintf("select %s from %s where `problem_id` = ? limit 1", problemVersionSeqRows, m.table)
	var resp ProblemVersionSeq
	err := m.conn.QueryRowCtx(ctx, &resp, query, problemId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemVersionSeqModel) Insert(ctx context.Context, data *ProblemVersionSeq) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, problemVersionSeqRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProblemId, data.NextVersion)
	return ret, err
}

func (m *defaultProblemVersionSeqModel) Update(ctx context.Context, data *ProblemVersionSeq) error {
	query := fmt.Sprintf("update %s set %s where `problem_id` = ?", m.table, problemVersionSeqRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.NextVersion, data.ProblemId)
	return err
}

func (m *defaultProblemVersionSeqModel) tableName() string {
	return m.table
}
