// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemVersionFieldNames          = builder.RawFieldNames(&ProblemVersion{})
	problemVersionRows                = strings.Join(problemVersionFieldNames, ",")
	problemVersionRowsExpectAutoSet   = strings.Join(stringx.Remove(problemVersionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemVersionRowsWithPlaceHolder = strings.Join(stringx.Remove(problemVersionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemVersionModel interface {
		Insert(ctx context.Context, data *ProblemVersion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProblemVersion, error)
		FindOneByProblemIdVersion(ctx context.Context, problemId int64, version int64) (*ProblemVersion, error)
		Update(ctx context.Context, data *ProblemVersion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProblemVersionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProblemVersion struct {
		Id           int64     `db:"id"`
		ProblemId    int64     `db:"problem_id"`
		Version      int64     `db:"version"`
		State        int64     `db:"state"` // 0=draft,1=published
		ConfigJson   string    `db:"config_json"`
		ManifestHash string    `db:"manifest_hash"`
		DataPackKey  string    `db:"data_pack_key"`
		DataPackHash string    `db:"data_pack_hash"`
		CreatedAt    time.Time `db:"created_at"`
	}
)

func newProblemVersionModel(conn sqlx.SqlConn) *defaultProblemVersionModel {
	return &defaultProblemVersionModel{
		conn:  conn,
		table: "`problem_version`",
	}
}

func (m *defaultProblemVersionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemVersionModel) FindOne(ctx context.Context, id int64) (*ProblemVersion, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemVersionRows, m.table)
	var resp ProblemVersion
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemVersionModel) FindOneByProblemIdVersion(ctx context.Context, problemId int64, version int64) (*ProblemVersion, error) {
	var resp ProblemVersion
	query := fmt.Sprintf("select %s from %s where `problem_id` = ? and `version` = ? limit 1", problemVersionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, problemId, version)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemVersionModel) Insert(ctx context.Context, data *ProblemVersion) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, problemVersionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProblemId, data.Version, data.State, data.ConfigJson, data.ManifestHash, data.DataPackKey, data.DataPackHash)
	return ret, err
}

func (m *defaultProblemVersionModel) Update(ctx context.Context, newData *ProblemVersion) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemVersionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProblemId, newData.Version, newData.State, newData.ConfigJson, newData.ManifestHash, newData.DataPackKey, newData.DataPackHash, newData.Id)
	return err
}

func (m *defaultProblemVersionModel) tableName() string {
	return m.table
}
