// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemDataPackUploadFieldNames          = builder.RawFieldNames(&ProblemDataPackUpload{})
	problemDataPackUploadRows                = strings.Join(problemDataPackUploadFieldNames, ",")
	problemDataPackUploadRowsExpectAutoSet   = strings.Join(stringx.Remove(problemDataPackUploadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemDataPackUploadRowsWithPlaceHolder = strings.Join(stringx.Remove(problemDataPackUploadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemDataPackUploadModel interface {
		Insert(ctx context.Context, data *ProblemDataPackUpload) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProblemDataPackUpload, error)
		FindOneByProblemIdIdempotencyKey(ctx context.Context, problemId int64, idempotencyKey string) (*ProblemDataPackUpload, error)
		FindOneByProblemIdVersion(ctx context.Context, problemId int64, version int64) (*ProblemDataPackUpload, error)
		Update(ctx context.Context, data *ProblemDataPackUpload) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProblemDataPackUploadModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProblemDataPackUpload struct {
		Id                int64     `db:"id"`
		ProblemId         int64     `db:"problem_id"`
		Version           int64     `db:"version"`
		IdempotencyKey    string    `db:"idempotency_key"`
		Bucket            string    `db:"bucket"`
		ObjectKey         string    `db:"object_key"`
		UploadId          string    `db:"upload_id"` // MinIO multipart upload id
		ExpectedSizeBytes int64     `db:"expected_size_bytes"`
		ExpectedSha256    string    `db:"expected_sha256"`
		ContentType       string    `db:"content_type"`
		State             int64     `db:"state"` // 0=uploading,1=completed,2=aborted,3=expired
		ExpiresAt         time.Time `db:"expires_at"`
		CreatedBy         int64     `db:"created_by"`
		CreatedAt         time.Time `db:"created_at"`
		UpdatedAt         time.Time `db:"updated_at"`
	}
)

func newProblemDataPackUploadModel(conn sqlx.SqlConn) *defaultProblemDataPackUploadModel {
	return &defaultProblemDataPackUploadModel{
		conn:  conn,
		table: "`problem_data_pack_upload`",
	}
}

func (m *defaultProblemDataPackUploadModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemDataPackUploadModel) FindOne(ctx context.Context, id int64) (*ProblemDataPackUpload, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemDataPackUploadRows, m.table)
	var resp ProblemDataPackUpload
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemDataPackUploadModel) FindOneByProblemIdIdempotencyKey(ctx context.Context, problemId int64, idempotencyKey string) (*ProblemDataPackUpload, error) {
	var resp ProblemDataPackUpload
	query := fmt.Sprintf("select %s from %s where `problem_id` = ? and `idempotency_key` = ? limit 1", problemDataPackUploadRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, problemId, idempotencyKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemDataPackUploadModel) FindOneByProblemIdVersion(ctx context.Context, problemId int64, version int64) (*ProblemDataPackUpload, error) {
	var resp ProblemDataPackUpload
	query := fmt.Sprintf("select %s from %s where `problem_id` = ? and `version` = ? limit 1", problemDataPackUploadRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, problemId, version)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemDataPackUploadModel) Insert(ctx context.Context, data *ProblemDataPackUpload) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, problemDataPackUploadRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProblemId, data.Version, data.IdempotencyKey, data.Bucket, data.ObjectKey, data.UploadId, data.ExpectedSizeBytes, data.ExpectedSha256, data.ContentType, data.State, data.ExpiresAt, data.CreatedBy)
	return ret, err
}

func (m *defaultProblemDataPackUploadModel) Update(ctx context.Context, newData *ProblemDataPackUpload) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemDataPackUploadRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProblemId, newData.Version, newData.IdempotencyKey, newData.Bucket, newData.ObjectKey, newData.UploadId, newData.ExpectedSizeBytes, newData.ExpectedSha256, newData.ContentType, newData.State, newData.ExpiresAt, newData.CreatedBy, newData.Id)
	return err
}

func (m *defaultProblemDataPackUploadModel) tableName() string {
	return m.table
}
