// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemFieldNames          = builder.RawFieldNames(&Problem{})
	problemRows                = strings.Join(problemFieldNames, ",")
	problemRowsExpectAutoSet   = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemRowsWithPlaceHolder = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemModel interface {
		Insert(ctx context.Context, data *Problem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Problem, error)
		Update(ctx context.Context, data *Problem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProblemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Problem struct {
		Id        int64     `db:"id"`
		Title     string    `db:"title"`
		Status    int64     `db:"status"` // 0=draft,1=published,2=archived
		OwnerId   int64     `db:"owner_id"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newProblemModel(conn sqlx.SqlConn) *defaultProblemModel {
	return &defaultProblemModel{
		conn:  conn,
		table: "`problem`",
	}
}

func (m *defaultProblemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemModel) FindOne(ctx context.Context, id int64) (*Problem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemRows, m.table)
	var resp Problem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemModel) Insert(ctx context.Context, data *Problem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, problemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Status, data.OwnerId)
	return ret, err
}

func (m *defaultProblemModel) Update(ctx context.Context, data *Problem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Status, data.OwnerId, data.Id)
	return err
}

func (m *defaultProblemModel) tableName() string {
	return m.table
}
