// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddContestProblemRequest struct {
	Id        string `path:"id"`
	ProblemId int64  `json:"problem_id"`
	Order     int    `json:"order"`
	Score     int    `json:"score"`
	Visible   bool   `json:"visible"`
	Version   int32  `json:"version"`
}

type AnnouncementInfo struct {
	AnnouncementId string `json:"announcement_id"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	CreatedAt      string `json:"created_at"`
}

type ApproveContestRequest struct {
	Id     string `path:"id"`
	UserId int64  `json:"user_id"`
	Action string `json:"action"`
	Reason string `json:"reason"`
}

type ContestDetail struct {
	ContestId   string             `json:"contest_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Visibility  string             `json:"visibility"`
	OwnerId     int64              `json:"owner_id"`
	OrgId       int64              `json:"org_id"`
	StartAt     string             `json:"start_at"`
	EndAt       string             `json:"end_at"`
	Rule        ContestRulePayload `json:"rule"`
	CreatedAt   string             `json:"created_at"`
	UpdatedAt   string             `json:"updated_at"`
}

type ContestProblemInfo struct {
	ProblemId int64 `json:"problem_id"`
	Order     int   `json:"order"`
	Score     int   `json:"score"`
	Visible   bool  `json:"visible"`
	Version   int32 `json:"version"`
}

type ContestResultPayload struct {
	MemberId     string         `json:"member_id"`
	Rank         int            `json:"rank"`
	Score        int64          `json:"score"`
	TotalPenalty int64          `json:"total_penalty"`
	AcCount      int            `json:"ac_count"`
	Details      []ResultDetail `json:"details"`
}

type ContestRulePayload struct {
	RuleType                    string `json:"rule_type"`
	PenaltyMinutes              int    `json:"penalty_minutes"`
	PenaltyFormula              string `json:"penalty_formula"`
	PenaltyCapMinutes           int    `json:"penalty_cap_minutes"`
	FreezeMinutesBeforeEnd      int    `json:"freeze_minutes_before_end"`
	AllowHack                   bool   `json:"allow_hack"`
	HackReward                  int    `json:"hack_reward"`
	HackPenalty                 int    `json:"hack_penalty"`
	MaxSubmissionsPerProblem    int    `json:"max_submissions_per_problem"`
	ScoreMode                   string `json:"score_mode"`
	PublishSolutionsAfterEnd    bool   `json:"publish_solutions_after_end"`
	VirtualParticipationEnabled bool   `json:"virtual_participation_enabled"`
}

type ContestSummary struct {
	ContestId string `json:"contest_id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	RuleType  string `json:"rule_type"`
	StartAt   string `json:"start_at"`
	EndAt     string `json:"end_at"`
}

type CreateAnnouncementPayload struct {
	AnnouncementId string `json:"announcement_id"`
}

type CreateAnnouncementRequest struct {
	Id      string `path:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	UserId  int64  `json:"user_id"`
}

type CreateAnnouncementResponse struct {
	Code    int                       `json:"code"`
	Message string                    `json:"message"`
	Data    CreateAnnouncementPayload `json:"data"`
	Details map[string]string         `json:"details,omitempty"`
	TraceId string                    `json:"trace_id,omitempty"`
}

type CreateContestPayload struct {
	ContestId string `json:"contest_id"`
}

type CreateContestRequest struct {
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Visibility  string             `json:"visibility"`
	OwnerId     int64              `json:"owner_id"`
	OrgId       int64              `json:"org_id"`
	StartAt     string             `json:"start_at"`
	EndAt       string             `json:"end_at"`
	Rule        ContestRulePayload `json:"rule"`
}

type CreateContestResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    CreateContestPayload `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type CreateHackPayload struct {
	HackId string `json:"hack_id"`
}

type CreateHackRequest struct {
	Id                 string `path:"id"`
	ProblemId          int64  `json:"problem_id"`
	TargetSubmissionId string `json:"target_submission_id"`
	UserId             int64  `json:"user_id"`
	Data               string `json:"data"`
}

type CreateHackResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    CreateHackPayload `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type CreateTeamPayload struct {
	TeamId string `json:"team_id"`
}

type CreateTeamRequest struct {
	Id       string `path:"id"`
	Name     string `json:"name"`
	LeaderId int64  `json:"leader_id"`
}

type CreateTeamResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    CreateTeamPayload `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type GetContestRequest struct {
	Id string `path:"id"`
}

type GetContestResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    ContestDetail     `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type GetHackRequest struct {
	Id     string `path:"id"`
	HackId string `path:"hack_id"`
}

type GetHackResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    HackInfo          `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type HackInfo struct {
	HackId             string `json:"hack_id"`
	Status             string `json:"status"`
	ProblemId          int64  `json:"problem_id"`
	TargetSubmissionId string `json:"target_submission_id"`
	UserId             int64  `json:"user_id"`
	CreatedAt          string `json:"created_at"`
}

type JoinTeamRequest struct {
	Id     string `path:"id"`
	TeamId string `path:"team_id"`
	UserId int64  `json:"user_id"`
}

type LeaderboardEntry struct {
	MemberId string            `json:"member_id"`
	Rank     int               `json:"rank"`
	Score    int64             `json:"score"`
	Penalty  int64             `json:"penalty"`
	Detail   map[string]string `json:"detail"`
}

type LeaderboardPayload struct {
	Items []LeaderboardEntry `json:"items"`
	Page  PageInfo           `json:"page"`
}

type LeaderboardReplayRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	At       int64  `form:"at"`
}

type LeaderboardRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}

type LeaderboardResponse struct {
	Code    int                `json:"code"`
	Message string             `json:"message"`
	Data    LeaderboardPayload `json:"data"`
	Details map[string]string  `json:"details,omitempty"`
	TraceId string             `json:"trace_id,omitempty"`
}

type LeaveTeamRequest struct {
	Id     string `path:"id"`
	TeamId string `path:"team_id"`
	UserId int64  `json:"user_id"`
}

type ListAnnouncementsPayload struct {
	Items []AnnouncementInfo `json:"items"`
	Page  PageInfo           `json:"page"`
}

type ListAnnouncementsRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}

type ListAnnouncementsResponse struct {
	Code    int                      `json:"code"`
	Message string                   `json:"message"`
	Data    ListAnnouncementsPayload `json:"data"`
	Details map[string]string        `json:"details,omitempty"`
	TraceId string                   `json:"trace_id,omitempty"`
}

type ListContestProblemsRequest struct {
	Id string `path:"id"`
}

type ListContestProblemsResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    []ContestProblemInfo `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type ListContestsPayload struct {
	Items []ContestSummary `json:"items"`
	Page  PageInfo         `json:"page"`
}

type ListContestsRequest struct {
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	Status   string `form:"status"`
	OwnerId  int64  `form:"owner_id"`
	OrgId    int64  `form:"org_id"`
}

type ListContestsResponse struct {
	Code    int                 `json:"code"`
	Message string              `json:"message"`
	Data    ListContestsPayload `json:"data"`
	Details map[string]string   `json:"details,omitempty"`
	TraceId string              `json:"trace_id,omitempty"`
}

type ListParticipantsPayload struct {
	Items []ParticipantInfo `json:"items"`
	Page  PageInfo          `json:"page"`
}

type ListParticipantsRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}

type ListParticipantsResponse struct {
	Code    int                     `json:"code"`
	Message string                  `json:"message"`
	Data    ListParticipantsPayload `json:"data"`
	Details map[string]string       `json:"details,omitempty"`
	TraceId string                  `json:"trace_id,omitempty"`
}

type ListTeamsPayload struct {
	Items []TeamInfo `json:"items"`
	Page  PageInfo   `json:"page"`
}

type ListTeamsRequest struct {
	Id       string `path:"id"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}

type ListTeamsResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    ListTeamsPayload  `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type MemberResultRequest struct {
	Id       string `path:"id"`
	MemberId string `path:"member_id"`
}

type MyResultRequest struct {
	Id string `path:"id"`
}

type MyResultResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    ContestResultPayload `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type PageInfo struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
	Total    int `json:"total"`
}

type ParticipantInfo struct {
	UserId   int64  `json:"user_id"`
	TeamId   string `json:"team_id"`
	Status   string `json:"status"`
	JoinedAt string `json:"joined_at"`
}

type QuitContestRequest struct {
	Id     string `path:"id"`
	UserId int64  `json:"user_id"`
}

type RegisterContestRequest struct {
	Id         string `path:"id"`
	UserId     int64  `json:"user_id"`
	TeamId     string `json:"team_id"`
	InviteCode string `json:"invite_code"`
}

type RemoveContestProblemRequest struct {
	Id        string `path:"id"`
	ProblemId int64  `path:"problem_id"`
}

type ResultDetail struct {
	ProblemId      int64  `json:"problem_id"`
	Status         string `json:"status"`
	FirstAcAt      string `json:"first_ac_at"`
	WrongAttempts  int    `json:"wrong_attempts"`
	PenaltyMinutes int64  `json:"penalty_minutes"`
}

type SuccessResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type TeamInfo struct {
	TeamId    string `json:"team_id"`
	Name      string `json:"name"`
	LeaderId  int64  `json:"leader_id"`
	MemberCnt int    `json:"member_cnt"`
}

type UpdateContestProblemRequest struct {
	Id        string `path:"id"`
	ProblemId int64  `path:"problem_id"`
	Order     int    `json:"order"`
	Score     int    `json:"score"`
	Visible   bool   `json:"visible"`
}

type UpdateContestRequest struct {
	Id          string             `path:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Visibility  string             `json:"visibility"`
	StartAt     string             `json:"start_at"`
	EndAt       string             `json:"end_at"`
	Rule        ContestRulePayload `json:"rule"`
}
