// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: contest.proto

package contestrpc

import (
	"context"

	contestpb "fuzoj/api/proto/contest"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckParticipationRequest  = contestpb.CheckParticipationRequest
	CheckParticipationResponse = contestpb.CheckParticipationResponse
	ContestMetaRequest         = contestpb.ContestMetaRequest
	ContestMetaResponse        = contestpb.ContestMetaResponse
	ContestProblem             = contestpb.ContestProblem
	ContestProblemsRequest     = contestpb.ContestProblemsRequest
	ContestProblemsResponse    = contestpb.ContestProblemsResponse
	ContestRule                = contestpb.ContestRule
	ContestRuleRequest         = contestpb.ContestRuleRequest
	ContestRuleResponse        = contestpb.ContestRuleResponse

	ContestRpc interface {
		CheckParticipation(ctx context.Context, in *CheckParticipationRequest, opts ...grpc.CallOption) (*CheckParticipationResponse, error)
		GetContestMeta(ctx context.Context, in *ContestMetaRequest, opts ...grpc.CallOption) (*ContestMetaResponse, error)
		GetContestRule(ctx context.Context, in *ContestRuleRequest, opts ...grpc.CallOption) (*ContestRuleResponse, error)
		GetContestProblems(ctx context.Context, in *ContestProblemsRequest, opts ...grpc.CallOption) (*ContestProblemsResponse, error)
	}

	defaultContestRpc struct {
		cli zrpc.Client
	}
)

func NewContestRpc(cli zrpc.Client) ContestRpc {
	return &defaultContestRpc{
		cli: cli,
	}
}

func (m *defaultContestRpc) CheckParticipation(ctx context.Context, in *CheckParticipationRequest, opts ...grpc.CallOption) (*CheckParticipationResponse, error) {
	client := contestpb.NewContestRpcClient(m.cli.Conn())
	return client.CheckParticipation(ctx, in, opts...)
}

func (m *defaultContestRpc) GetContestMeta(ctx context.Context, in *ContestMetaRequest, opts ...grpc.CallOption) (*ContestMetaResponse, error) {
	client := contestpb.NewContestRpcClient(m.cli.Conn())
	return client.GetContestMeta(ctx, in, opts...)
}

func (m *defaultContestRpc) GetContestRule(ctx context.Context, in *ContestRuleRequest, opts ...grpc.CallOption) (*ContestRuleResponse, error) {
	client := contestpb.NewContestRpcClient(m.cli.Conn())
	return client.GetContestRule(ctx, in, opts...)
}

func (m *defaultContestRpc) GetContestProblems(ctx context.Context, in *ContestProblemsRequest, opts ...grpc.CallOption) (*ContestProblemsResponse, error) {
	client := contestpb.NewContestRpcClient(m.cli.Conn())
	return client.GetContestProblems(ctx, in, opts...)
}
