// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userTokensFieldNames          = builder.RawFieldNames(&UserTokens{})
	userTokensRows                = strings.Join(userTokensFieldNames, ",")
	userTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(userTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userTokensRowsWithPlaceHolder = strings.Join(stringx.Remove(userTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserTokensIdPrefix        = "cache:userTokens:id:"
	cacheUserTokensTokenHashPrefix = "cache:userTokens:tokenHash:"
)

type (
	userTokensModel interface {
		Insert(ctx context.Context, data *UserTokens) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserTokens, error)
		FindOneByTokenHash(ctx context.Context, tokenHash string) (*UserTokens, error)
		Update(ctx context.Context, data *UserTokens) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserTokensModel struct {
		sqlc.CachedConn
		table string
	}

	UserTokens struct {
		Id         int64          `db:"id"`
		UserId     int64          `db:"user_id"`
		TokenHash  string         `db:"token_hash"`
		TokenType  string         `db:"token_type"`
		DeviceInfo sql.NullString `db:"device_info"`
		IpAddress  sql.NullString `db:"ip_address"`
		ExpiresAt  time.Time      `db:"expires_at"`
		Revoked    bool           `db:"revoked"`
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newUserTokensModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserTokensModel {
	return &defaultUserTokensModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_tokens`",
	}
}

func (m *defaultUserTokensModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userTokensIdKey := fmt.Sprintf("%s%v", cacheUserTokensIdPrefix, id)
	userTokensTokenHashKey := fmt.Sprintf("%s%v", cacheUserTokensTokenHashPrefix, data.TokenHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userTokensIdKey, userTokensTokenHashKey)
	return err
}

func (m *defaultUserTokensModel) FindOne(ctx context.Context, id int64) (*UserTokens, error) {
	userTokensIdKey := fmt.Sprintf("%s%v", cacheUserTokensIdPrefix, id)
	var resp UserTokens
	err := m.QueryRowCtx(ctx, &resp, userTokensIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTokensRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTokensModel) FindOneByTokenHash(ctx context.Context, tokenHash string) (*UserTokens, error) {
	userTokensTokenHashKey := fmt.Sprintf("%s%v", cacheUserTokensTokenHashPrefix, tokenHash)
	var resp UserTokens
	err := m.QueryRowIndexCtx(ctx, &resp, userTokensTokenHashKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `token_hash` = ? limit 1", userTokensRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tokenHash); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserTokensModel) Insert(ctx context.Context, data *UserTokens) (sql.Result, error) {
	userTokensIdKey := fmt.Sprintf("%s%v", cacheUserTokensIdPrefix, data.Id)
	userTokensTokenHashKey := fmt.Sprintf("%s%v", cacheUserTokensTokenHashPrefix, data.TokenHash)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userTokensRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TokenHash, data.TokenType, data.DeviceInfo, data.IpAddress, data.ExpiresAt, data.Revoked)
	}, userTokensIdKey, userTokensTokenHashKey)
	return ret, err
}

func (m *defaultUserTokensModel) Update(ctx context.Context, newData *UserTokens) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userTokensIdKey := fmt.Sprintf("%s%v", cacheUserTokensIdPrefix, data.Id)
	userTokensTokenHashKey := fmt.Sprintf("%s%v", cacheUserTokensTokenHashPrefix, data.TokenHash)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userTokensRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.TokenHash, newData.TokenType, newData.DeviceInfo, newData.IpAddress, newData.ExpiresAt, newData.Revoked, newData.Id)
	}, userTokensIdKey, userTokensTokenHashKey)
	return err
}

func (m *defaultUserTokensModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserTokensIdPrefix, primary)
}

func (m *defaultUserTokensModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userTokensRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserTokensModel) tableName() string {
	return m.table
}
