// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BatchStatusData struct {
	Items   []JudgeStatusData `json:"items"`
	Missing []string          `json:"missing"`
}

type BatchStatusRequest struct {
	SubmissionIds []string `json:"submission_ids"`
}

type BatchStatusResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    BatchStatusData   `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type CompileResult struct {
	OK       bool   `json:"OK"`
	ExitCode int    `json:"ExitCode"`
	TimeMs   int64  `json:"TimeMs"`
	MemoryKB int64  `json:"MemoryKB"`
	Log      string `json:"Log"`
	Error    string `json:"Error"`
}

type CreateSubmissionData struct {
	SubmissionId string `json:"submission_id"`
	Status       string `json:"status"`
	ReceivedAt   int64  `json:"received_at"`
}

type CreateSubmissionRequest struct {
	ProblemId         int64    `json:"problem_id"`
	UserId            int64    `json:"user_id"`
	LanguageId        string   `json:"language_id"`
	SourceCode        string   `json:"source_code"`
	ContestId         string   `json:"contest_id"`
	Scene             string   `json:"scene"`
	ExtraCompileFlags []string `json:"extra_compile_flags"`
	IdempotencyKey    string   `header:"Idempotency-Key"`
}

type CreateSubmissionResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    CreateSubmissionData `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type GetSourceRequest struct {
	Id string `path:"id"`
}

type GetSourceResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    SourceData        `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type GetStatusRequest struct {
	Id      string `path:"id"`
	Include string `form:"include,optional"`
}

type GetStatusResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    JudgeStatusData   `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type JudgeStatusData struct {
	SubmissionId string           `json:"submission_id"`
	Status       string           `json:"status"`
	Verdict      string           `json:"verdict"`
	Score        int              `json:"score"`
	Language     string           `json:"language"`
	Summary      SummaryStat      `json:"summary"`
	Compile      *CompileResult   `json:"compile,omitempty"`
	Tests        []TestcaseResult `json:"tests,omitempty"`
	Timestamps   Timestamps       `json:"timestamps"`
	Progress     Progress         `json:"progress"`
	ErrorCode    int              `json:"error_code,omitempty"`
	ErrorMessage string           `json:"error_message,omitempty"`
}

type Progress struct {
	TotalTests int `json:"total_tests"`
	DoneTests  int `json:"done_tests"`
}

type SourceData struct {
	SubmissionId string `json:"submission_id"`
	ProblemId    int64  `json:"problem_id"`
	UserId       int64  `json:"user_id"`
	ContestId    string `json:"contest_id,omitempty"`
	LanguageId   string `json:"language_id"`
	SourceCode   string `json:"source_code"`
	CreatedAt    string `json:"created_at"`
}

type SuccessResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type SummaryStat struct {
	TotalTimeMs  int64  `json:"TotalTimeMs"`
	MaxMemoryKB  int64  `json:"MaxMemoryKB"`
	TotalScore   int    `json:"TotalScore"`
	FailedTestID string `json:"FailedTestID"`
}

type TestcaseResult struct {
	TestID     string `json:"TestID"`
	Verdict    string `json:"Verdict"`
	TimeMs     int64  `json:"TimeMs"`
	MemoryKB   int64  `json:"MemoryKB"`
	OutputKB   int64  `json:"OutputKB"`
	ExitCode   int    `json:"ExitCode"`
	RuntimeLog string `json:"RuntimeLog"`
	CheckerLog string `json:"CheckerLog"`
	Stdout     string `json:"Stdout"`
	Stderr     string `json:"Stderr"`
	Score      int    `json:"Score"`
	SubtaskID  string `json:"SubtaskID"`
}

type Timestamps struct {
	ReceivedAt int64 `json:"ReceivedAt"`
	FinishedAt int64 `json:"FinishedAt"`
}
