// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	submissionsFieldNames          = builder.RawFieldNames(&Submissions{})
	submissionsRows                = strings.Join(submissionsFieldNames, ",")
	submissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(submissionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	submissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(submissionsFieldNames, "`submission_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSubmissionsSubmissionIdPrefix = "cache:submissions:submissionId:"
)

type (
	submissionsModel interface {
		Insert(ctx context.Context, data *Submissions) (sql.Result, error)
		FindOne(ctx context.Context, submissionId string) (*Submissions, error)
		Update(ctx context.Context, data *Submissions) error
		Delete(ctx context.Context, submissionId string) error
	}

	defaultSubmissionsModel struct {
		sqlc.CachedConn
		table string
	}

	Submissions struct {
		SubmissionId  string         `db:"submission_id"`
		ProblemId     int64          `db:"problem_id"`
		UserId        int64          `db:"user_id"`
		ContestId     sql.NullString `db:"contest_id"`
		LanguageId    string         `db:"language_id"`
		SourceCode    string         `db:"source_code"`
		SourceKey     string         `db:"source_key"`
		SourceHash    string         `db:"source_hash"`
		Scene         string         `db:"scene"`
		FinalStatus   sql.NullString `db:"final_status"`
		FinalStatusAt sql.NullTime   `db:"final_status_at"`
		CreatedAt     time.Time      `db:"created_at"`
	}
)

func newSubmissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSubmissionsModel {
	return &defaultSubmissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`submissions`",
	}
}

func (m *defaultSubmissionsModel) Delete(ctx context.Context, submissionId string) error {
	submissionsSubmissionIdKey := fmt.Sprintf("%s%v", cacheSubmissionsSubmissionIdPrefix, submissionId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `submission_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, submissionId)
	}, submissionsSubmissionIdKey)
	return err
}

func (m *defaultSubmissionsModel) FindOne(ctx context.Context, submissionId string) (*Submissions, error) {
	submissionsSubmissionIdKey := fmt.Sprintf("%s%v", cacheSubmissionsSubmissionIdPrefix, submissionId)
	var resp Submissions
	err := m.QueryRowCtx(ctx, &resp, submissionsSubmissionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `submission_id` = ? limit 1", submissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, submissionId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubmissionsModel) Insert(ctx context.Context, data *Submissions) (sql.Result, error) {
	submissionsSubmissionIdKey := fmt.Sprintf("%s%v", cacheSubmissionsSubmissionIdPrefix, data.SubmissionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, submissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SubmissionId, data.ProblemId, data.UserId, data.ContestId, data.LanguageId, data.SourceCode, data.SourceKey, data.SourceHash, data.Scene, data.FinalStatus, data.FinalStatusAt)
	}, submissionsSubmissionIdKey)
	return ret, err
}

func (m *defaultSubmissionsModel) Update(ctx context.Context, data *Submissions) error {
	submissionsSubmissionIdKey := fmt.Sprintf("%s%v", cacheSubmissionsSubmissionIdPrefix, data.SubmissionId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `submission_id` = ?", m.table, submissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProblemId, data.UserId, data.ContestId, data.LanguageId, data.SourceCode, data.SourceKey, data.SourceHash, data.Scene, data.FinalStatus, data.FinalStatusAt, data.SubmissionId)
	}, submissionsSubmissionIdKey)
	return err
}

func (m *defaultSubmissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSubmissionsSubmissionIdPrefix, primary)
}

func (m *defaultSubmissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `submission_id` = ? limit 1", submissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSubmissionsModel) tableName() string {
	return m.table
}
