// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fuzoj/services/contest_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/announcements",
				Handler: AnnouncementCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/announcements",
				Handler: AnnouncementListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/approve",
				Handler: ApproveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/close",
				Handler: CloseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/hacks",
				Handler: HackCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/hacks/:hack_id",
				Handler: HackGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/leaderboard",
				Handler: LeaderboardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/leaderboard/frozen",
				Handler: LeaderboardFrozenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/leaderboard/replay",
				Handler: LeaderboardReplayHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/my_result",
				Handler: MyResultHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/participants",
				Handler: ParticipantsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/problems",
				Handler: ProblemAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/problems",
				Handler: ProblemListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/:id/problems/:problem_id",
				Handler: ProblemUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id/problems/:problem_id",
				Handler: ProblemRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/publish",
				Handler: PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/quit",
				Handler: QuitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/results/:member_id",
				Handler: MemberResultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/teams",
				Handler: TeamCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/teams",
				Handler: TeamListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/teams/:team_id/join",
				Handler: TeamJoinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/teams/:team_id/leave",
				Handler: TeamLeaveHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/contests"),
	)
}
