// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthPayload struct {
	AccessToken      string   `json:"access_token"`
	RefreshToken     string   `json:"refresh_token"`
	AccessExpiresAt  string   `json:"access_expires_at"`
	RefreshExpiresAt string   `json:"refresh_expires_at"`
	User             UserInfo `json:"user"`
}

type AuthResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    AuthPayload       `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type LoginRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	IP         string `json:"-"`
	DeviceInfo string `json:"-"`
}

type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SuccessResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}
