// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AbortUploadRequest struct {
	Id       int64 `path:"id"`
	UploadId int64 `path:"upload_id"`
}

type CompleteUploadPayload struct {
	ProblemId    int64  `json:"problem_id"`
	Version      int32  `json:"version"`
	ManifestHash string `json:"manifest_hash"`
	DataPackKey  string `json:"data_pack_key"`
	DataPackHash string `json:"data_pack_hash"`
}

type CompleteUploadRequest struct {
	Id           int64                `path:"id"`
	UploadId     int64                `path:"upload_id"`
	Parts        []CompletedPartInput `json:"parts"`
	ManifestJson string               `json:"manifest_json"`
	ConfigJson   string               `json:"config_json"`
	ManifestHash string               `json:"manifest_hash"`
	DataPackHash string               `json:"data_pack_hash"`
}

type CompleteUploadResponse struct {
	Code    int                   `json:"code"`
	Message string                `json:"message"`
	Data    CompleteUploadPayload `json:"data"`
	Details map[string]string     `json:"details,omitempty"`
	TraceId string                `json:"trace_id,omitempty"`
}

type CompletedPartInput struct {
	PartNumber int    `json:"part_number"`
	ETag       string `json:"etag"`
}

type CreateProblemPayload struct {
	Id int64 `json:"id"`
}

type CreateProblemRequest struct {
	Title   string `json:"title"`
	OwnerId int64  `json:"owner_id"`
}

type CreateProblemResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    CreateProblemPayload `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type DeleteProblemRequest struct {
	Id int64 `path:"id"`
}

type GetLatestRequest struct {
	Id int64 `path:"id"`
}

type LatestMetaPayload struct {
	ProblemId    int64  `json:"problem_id"`
	Version      int32  `json:"version"`
	ManifestHash string `json:"manifest_hash"`
	DataPackKey  string `json:"data_pack_key"`
	DataPackHash string `json:"data_pack_hash"`
	UpdatedAt    string `json:"updated_at"`
}

type LatestMetaResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    LatestMetaPayload `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type PrepareUploadPayload struct {
	UploadId          int64  `json:"upload_id"`
	ProblemId         int64  `json:"problem_id"`
	Version           int32  `json:"version"`
	Bucket            string `json:"bucket"`
	ObjectKey         string `json:"object_key"`
	MultipartUploadId string `json:"multipart_upload_id"`
	PartSizeBytes     int64  `json:"part_size_bytes"`
	ExpiresAt         string `json:"expires_at"`
}

type PrepareUploadRequest struct {
	Id                int64  `path:"id"`
	IdempotencyKey    string `header:"Idempotency-Key"`
	ExpectedSizeBytes int64  `json:"expected_size_bytes"`
	ExpectedSha256    string `json:"expected_sha256"`
	ContentType       string `json:"content_type"`
	CreatedBy         int64  `json:"created_by"`
	ClientType        string `json:"client_type"`
	UploadStrategy    string `json:"upload_strategy"`
}

type PrepareUploadResponse struct {
	Code    int                  `json:"code"`
	Message string               `json:"message"`
	Data    PrepareUploadPayload `json:"data"`
	Details map[string]string    `json:"details,omitempty"`
	TraceId string               `json:"trace_id,omitempty"`
}

type PublishVersionRequest struct {
	Id      int64 `path:"id"`
	Version int32 `path:"version"`
}

type SignPartsPayload struct {
	Urls             map[string]string `json:"urls"`
	ExpiresInSeconds int64             `json:"expires_in_seconds"`
}

type SignPartsRequest struct {
	Id          int64 `path:"id"`
	UploadId    int64 `path:"upload_id"`
	PartNumbers []int `json:"part_numbers"`
}

type SignPartsResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    SignPartsPayload  `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type SuccessResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}
