// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/rank/rank.proto

package rank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Rank          int64                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Penalty       int64                  `protobuf:"varint,4,opt,name=penalty,proto3" json:"penalty,omitempty"`
	DetailJson    string                 `protobuf:"bytes,5,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardEntry) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *LeaderboardEntry) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetPenalty() int64 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *LeaderboardEntry) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *GetLeaderboardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLeaderboardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLeaderboardRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type LeaderboardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardReply) Reset() {
	*x = LeaderboardReply{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardReply) ProtoMessage() {}

func (x *LeaderboardReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardReply.ProtoReflect.Descriptor instead.
func (*LeaderboardReply) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderboardReply) GetItems() []*LeaderboardEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LeaderboardReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *LeaderboardReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetMemberRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRankRequest) Reset() {
	*x = GetMemberRankRequest{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRankRequest) ProtoMessage() {}

func (x *GetMemberRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRankRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRankRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemberRankRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *GetMemberRankRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetMemberRankRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MemberRankReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LeaderboardEntry      `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRankReply) Reset() {
	*x = MemberRankReply{}
	mi := &file_api_proto_rank_rank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRankReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRankReply) ProtoMessage() {}

func (x *MemberRankReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rank_rank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRankReply.ProtoReflect.Descriptor instead.
func (*MemberRankReply) Descriptor() ([]byte, []int) {
	return file_api_proto_rank_rank_proto_rawDescGZIP(), []int{5}
}

func (x *MemberRankReply) GetEntry() *LeaderboardEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *MemberRankReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemberRankReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_proto_rank_rank_proto protoreflect.FileDescriptor

const file_api_proto_rank_rank_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/rank/rank.proto\x12\x04rank\"\x94\x01\n" +
	"\x10LeaderboardEntry\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x03R\x04rank\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x18\n" +
	"\apenalty\x18\x04 \x01(\x03R\apenalty\x12\x1f\n" +
	"\vdetail_json\x18\x05 \x01(\tR\n" +
	"detailJson\"Q\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"{\n" +
	"\x15GetLeaderboardRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"~\n" +
	"\x10LeaderboardReply\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.rank.LeaderboardEntryR\x05items\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.rank.PageInfoR\x04page\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"f\n" +
	"\x14GetMemberRankRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"o\n" +
	"\x0fMemberRankReply\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.rank.LeaderboardEntryR\x05entry\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\x94\x01\n" +
	"\aRankRpc\x12E\n" +
	"\x0eGetLeaderboard\x12\x1b.rank.GetLeaderboardRequest\x1a\x16.rank.LeaderboardReply\x12B\n" +
	"\rGetMemberRank\x12\x1a.rank.GetMemberRankRequest\x1a\x15.rank.MemberRankReplyB\x1bZ\x19fuzoj/api/proto/rank;rankb\x06proto3"

var (
	file_api_proto_rank_rank_proto_rawDescOnce sync.Once
	file_api_proto_rank_rank_proto_rawDescData []byte
)

func file_api_proto_rank_rank_proto_rawDescGZIP() []byte {
	file_api_proto_rank_rank_proto_rawDescOnce.Do(func() {
		file_api_proto_rank_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rank_rank_proto_rawDesc), len(file_api_proto_rank_rank_proto_rawDesc)))
	})
	return file_api_proto_rank_rank_proto_rawDescData
}

var file_api_proto_rank_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_rank_rank_proto_goTypes = []any{
	(*LeaderboardEntry)(nil),      // 0: rank.LeaderboardEntry
	(*PageInfo)(nil),              // 1: rank.PageInfo
	(*GetLeaderboardRequest)(nil), // 2: rank.GetLeaderboardRequest
	(*LeaderboardReply)(nil),      // 3: rank.LeaderboardReply
	(*GetMemberRankRequest)(nil),  // 4: rank.GetMemberRankRequest
	(*MemberRankReply)(nil),       // 5: rank.MemberRankReply
}
var file_api_proto_rank_rank_proto_depIdxs = []int32{
	0, // 0: rank.LeaderboardReply.items:type_name -> rank.LeaderboardEntry
	1, // 1: rank.LeaderboardReply.page:type_name -> rank.PageInfo
	0, // 2: rank.MemberRankReply.entry:type_name -> rank.LeaderboardEntry
	2, // 3: rank.RankRpc.GetLeaderboard:input_type -> rank.GetLeaderboardRequest
	4, // 4: rank.RankRpc.GetMemberRank:input_type -> rank.GetMemberRankRequest
	3, // 5: rank.RankRpc.GetLeaderboard:output_type -> rank.LeaderboardReply
	5, // 6: rank.RankRpc.GetMemberRank:output_type -> rank.MemberRankReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_rank_rank_proto_init() }
func file_api_proto_rank_rank_proto_init() {
	if File_api_proto_rank_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rank_rank_proto_rawDesc), len(file_api_proto_rank_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rank_rank_proto_goTypes,
		DependencyIndexes: file_api_proto_rank_rank_proto_depIdxs,
		MessageInfos:      file_api_proto_rank_rank_proto_msgTypes,
	}.Build()
	File_api_proto_rank_rank_proto = out.File
	file_api_proto_rank_rank_proto_goTypes = nil
	file_api_proto_rank_rank_proto_depIdxs = nil
}
