// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/rank/rank.proto

package rank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankRpc_GetLeaderboard_FullMethodName = "/rank.RankRpc/GetLeaderboard"
	RankRpc_GetMemberRank_FullMethodName  = "/rank.RankRpc/GetMemberRank"
)

// RankRpcClient is the client API for RankRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankRpcClient interface {
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardReply, error)
	GetMemberRank(ctx context.Context, in *GetMemberRankRequest, opts ...grpc.CallOption) (*MemberRankReply, error)
}

type rankRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRankRpcClient(cc grpc.ClientConnInterface) RankRpcClient {
	return &rankRpcClient{cc}
}

func (c *rankRpcClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardReply)
	err := c.cc.Invoke(ctx, RankRpc_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankRpcClient) GetMemberRank(ctx context.Context, in *GetMemberRankRequest, opts ...grpc.CallOption) (*MemberRankReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberRankReply)
	err := c.cc.Invoke(ctx, RankRpc_GetMemberRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankRpcServer is the server API for RankRpc service.
// All implementations must embed UnimplementedRankRpcServer
// for forward compatibility.
type RankRpcServer interface {
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*LeaderboardReply, error)
	GetMemberRank(context.Context, *GetMemberRankRequest) (*MemberRankReply, error)
	mustEmbedUnimplementedRankRpcServer()
}

// UnimplementedRankRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankRpcServer struct{}

func (UnimplementedRankRpcServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*LeaderboardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedRankRpcServer) GetMemberRank(context.Context, *GetMemberRankRequest) (*MemberRankReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberRank not implemented")
}
func (UnimplementedRankRpcServer) mustEmbedUnimplementedRankRpcServer() {}
func (UnimplementedRankRpcServer) testEmbeddedByValue()                 {}

// UnsafeRankRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankRpcServer will
// result in compilation errors.
type UnsafeRankRpcServer interface {
	mustEmbedUnimplementedRankRpcServer()
}

func RegisterRankRpcServer(s grpc.ServiceRegistrar, srv RankRpcServer) {
	// If the following call panics, it indicates UnimplementedRankRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankRpc_ServiceDesc, srv)
}

func _RankRpc_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankRpcServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankRpc_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankRpcServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankRpc_GetMemberRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankRpcServer).GetMemberRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankRpc_GetMemberRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankRpcServer).GetMemberRank(ctx, req.(*GetMemberRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankRpc_ServiceDesc is the grpc.ServiceDesc for RankRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rank.RankRpc",
	HandlerType: (*RankRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaderboard",
			Handler:    _RankRpc_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetMemberRank",
			Handler:    _RankRpc_GetMemberRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/rank/rank.proto",
}
