// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CompileResult struct {
	OK       bool   `json:"OK"`
	ExitCode int    `json:"ExitCode"`
	TimeMs   int64  `json:"TimeMs"`
	MemoryKB int64  `json:"MemoryKB"`
	LogPath  string `json:"LogPath"`
	Error    string `json:"Error"`
}

type GetJudgeStatusRequest struct {
	Id string `path:"id"`
}

type JudgeStatusData struct {
	SubmissionId string           `json:"submission_id"`
	Status       string           `json:"status"`
	Verdict      string           `json:"verdict"`
	Score        int              `json:"score"`
	Language     string           `json:"language"`
	Summary      SummaryStat      `json:"summary"`
	Compile      *CompileResult   `json:"compile,omitempty"`
	Tests        []TestcaseResult `json:"tests,omitempty"`
	Timestamps   Timestamps       `json:"timestamps"`
	Progress     Progress         `json:"progress"`
	ErrorCode    int              `json:"error_code,omitempty"`
	ErrorMessage string           `json:"error_message,omitempty"`
}

type JudgeStatusResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Data    JudgeStatusData   `json:"data"`
	Details map[string]string `json:"details,omitempty"`
	TraceId string            `json:"trace_id,omitempty"`
}

type Progress struct {
	TotalTests int `json:"total_tests"`
	DoneTests  int `json:"done_tests"`
}

type SummaryStat struct {
	TotalTimeMs  int64  `json:"TotalTimeMs"`
	MaxMemoryKB  int64  `json:"MaxMemoryKB"`
	TotalScore   int    `json:"TotalScore"`
	FailedTestID string `json:"FailedTestID"`
}

type TestcaseResult struct {
	TestID         string `json:"TestID"`
	Verdict        string `json:"Verdict"`
	TimeMs         int64  `json:"TimeMs"`
	MemoryKB       int64  `json:"MemoryKB"`
	OutputKB       int64  `json:"OutputKB"`
	ExitCode       int    `json:"ExitCode"`
	RuntimeLogPath string `json:"RuntimeLogPath"`
	CheckerLogPath string `json:"CheckerLogPath"`
	Stdout         string `json:"Stdout"`
	Stderr         string `json:"Stderr"`
	Score          int    `json:"Score"`
	SubtaskID      string `json:"SubtaskID"`
}

type Timestamps struct {
	ReceivedAt int64 `json:"ReceivedAt"`
	FinishedAt int64 `json:"FinishedAt"`
}
