// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fuzoj/services/judge_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/submissions/:id",
				Handler: GetStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/judge"),
	)
}
