// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contest/contest.proto

package contest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckParticipationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProblemId     int64                  `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckParticipationRequest) Reset() {
	*x = CheckParticipationRequest{}
	mi := &file_contest_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckParticipationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckParticipationRequest) ProtoMessage() {}

func (x *CheckParticipationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckParticipationRequest.ProtoReflect.Descriptor instead.
func (*CheckParticipationRequest) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{0}
}

func (x *CheckParticipationRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *CheckParticipationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckParticipationRequest) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

type CheckParticipationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckParticipationResponse) Reset() {
	*x = CheckParticipationResponse{}
	mi := &file_contest_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckParticipationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckParticipationResponse) ProtoMessage() {}

func (x *CheckParticipationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckParticipationResponse.ProtoReflect.Descriptor instead.
func (*CheckParticipationResponse) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{1}
}

func (x *CheckParticipationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CheckParticipationResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CheckParticipationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ContestRule struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	RuleType                    string                 `protobuf:"bytes,1,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	PenaltyMinutes              int32                  `protobuf:"varint,2,opt,name=penalty_minutes,json=penaltyMinutes,proto3" json:"penalty_minutes,omitempty"`
	PenaltyFormula              string                 `protobuf:"bytes,3,opt,name=penalty_formula,json=penaltyFormula,proto3" json:"penalty_formula,omitempty"`
	PenaltyCapMinutes           int32                  `protobuf:"varint,4,opt,name=penalty_cap_minutes,json=penaltyCapMinutes,proto3" json:"penalty_cap_minutes,omitempty"`
	FreezeMinutesBeforeEnd      int32                  `protobuf:"varint,5,opt,name=freeze_minutes_before_end,json=freezeMinutesBeforeEnd,proto3" json:"freeze_minutes_before_end,omitempty"`
	AllowHack                   bool                   `protobuf:"varint,6,opt,name=allow_hack,json=allowHack,proto3" json:"allow_hack,omitempty"`
	HackReward                  int32                  `protobuf:"varint,7,opt,name=hack_reward,json=hackReward,proto3" json:"hack_reward,omitempty"`
	HackPenalty                 int32                  `protobuf:"varint,8,opt,name=hack_penalty,json=hackPenalty,proto3" json:"hack_penalty,omitempty"`
	MaxSubmissionsPerProblem    int32                  `protobuf:"varint,9,opt,name=max_submissions_per_problem,json=maxSubmissionsPerProblem,proto3" json:"max_submissions_per_problem,omitempty"`
	ScoreMode                   string                 `protobuf:"bytes,10,opt,name=score_mode,json=scoreMode,proto3" json:"score_mode,omitempty"`
	PublishSolutionsAfterEnd    bool                   `protobuf:"varint,11,opt,name=publish_solutions_after_end,json=publishSolutionsAfterEnd,proto3" json:"publish_solutions_after_end,omitempty"`
	VirtualParticipationEnabled bool                   `protobuf:"varint,12,opt,name=virtual_participation_enabled,json=virtualParticipationEnabled,proto3" json:"virtual_participation_enabled,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ContestRule) Reset() {
	*x = ContestRule{}
	mi := &file_contest_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestRule) ProtoMessage() {}

func (x *ContestRule) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestRule.ProtoReflect.Descriptor instead.
func (*ContestRule) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{2}
}

func (x *ContestRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *ContestRule) GetPenaltyMinutes() int32 {
	if x != nil {
		return x.PenaltyMinutes
	}
	return 0
}

func (x *ContestRule) GetPenaltyFormula() string {
	if x != nil {
		return x.PenaltyFormula
	}
	return ""
}

func (x *ContestRule) GetPenaltyCapMinutes() int32 {
	if x != nil {
		return x.PenaltyCapMinutes
	}
	return 0
}

func (x *ContestRule) GetFreezeMinutesBeforeEnd() int32 {
	if x != nil {
		return x.FreezeMinutesBeforeEnd
	}
	return 0
}

func (x *ContestRule) GetAllowHack() bool {
	if x != nil {
		return x.AllowHack
	}
	return false
}

func (x *ContestRule) GetHackReward() int32 {
	if x != nil {
		return x.HackReward
	}
	return 0
}

func (x *ContestRule) GetHackPenalty() int32 {
	if x != nil {
		return x.HackPenalty
	}
	return 0
}

func (x *ContestRule) GetMaxSubmissionsPerProblem() int32 {
	if x != nil {
		return x.MaxSubmissionsPerProblem
	}
	return 0
}

func (x *ContestRule) GetScoreMode() string {
	if x != nil {
		return x.ScoreMode
	}
	return ""
}

func (x *ContestRule) GetPublishSolutionsAfterEnd() bool {
	if x != nil {
		return x.PublishSolutionsAfterEnd
	}
	return false
}

func (x *ContestRule) GetVirtualParticipationEnabled() bool {
	if x != nil {
		return x.VirtualParticipationEnabled
	}
	return false
}

type ContestMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestMetaRequest) Reset() {
	*x = ContestMetaRequest{}
	mi := &file_contest_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestMetaRequest) ProtoMessage() {}

func (x *ContestMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestMetaRequest.ProtoReflect.Descriptor instead.
func (*ContestMetaRequest) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{3}
}

func (x *ContestMetaRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type ContestMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartAt       string                 `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         string                 `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Rule          *ContestRule           `protobuf:"bytes,6,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestMetaResponse) Reset() {
	*x = ContestMetaResponse{}
	mi := &file_contest_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestMetaResponse) ProtoMessage() {}

func (x *ContestMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestMetaResponse.ProtoReflect.Descriptor instead.
func (*ContestMetaResponse) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{4}
}

func (x *ContestMetaResponse) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *ContestMetaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContestMetaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContestMetaResponse) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *ContestMetaResponse) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *ContestMetaResponse) GetRule() *ContestRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ContestRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestRuleRequest) Reset() {
	*x = ContestRuleRequest{}
	mi := &file_contest_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestRuleRequest) ProtoMessage() {}

func (x *ContestRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestRuleRequest.ProtoReflect.Descriptor instead.
func (*ContestRuleRequest) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{5}
}

func (x *ContestRuleRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type ContestRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ContestRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestRuleResponse) Reset() {
	*x = ContestRuleResponse{}
	mi := &file_contest_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestRuleResponse) ProtoMessage() {}

func (x *ContestRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestRuleResponse.ProtoReflect.Descriptor instead.
func (*ContestRuleResponse) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{6}
}

func (x *ContestRuleResponse) GetRule() *ContestRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ContestProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Visible       bool                   `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestProblem) Reset() {
	*x = ContestProblem{}
	mi := &file_contest_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblem) ProtoMessage() {}

func (x *ContestProblem) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblem.ProtoReflect.Descriptor instead.
func (*ContestProblem) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{7}
}

func (x *ContestProblem) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ContestProblem) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ContestProblem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ContestProblem) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *ContestProblem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ContestProblemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestProblemsRequest) Reset() {
	*x = ContestProblemsRequest{}
	mi := &file_contest_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestProblemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblemsRequest) ProtoMessage() {}

func (x *ContestProblemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblemsRequest.ProtoReflect.Descriptor instead.
func (*ContestProblemsRequest) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{8}
}

func (x *ContestProblemsRequest) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

type ContestProblemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContestProblem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestProblemsResponse) Reset() {
	*x = ContestProblemsResponse{}
	mi := &file_contest_contest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestProblemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblemsResponse) ProtoMessage() {}

func (x *ContestProblemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contest_contest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblemsResponse.ProtoReflect.Descriptor instead.
func (*ContestProblemsResponse) Descriptor() ([]byte, []int) {
	return file_contest_contest_proto_rawDescGZIP(), []int{9}
}

func (x *ContestProblemsResponse) GetItems() []*ContestProblem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_contest_contest_proto protoreflect.FileDescriptor

const file_contest_contest_proto_rawDesc = "" +
	"\n" +
	"\x15contest/contest.proto\x12\acontest\"r\n" +
	"\x19CheckParticipationRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x03 \x01(\x03R\tproblemId\"p\n" +
	"\x1aCheckParticipationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xab\x04\n" +
	"\vContestRule\x12\x1b\n" +
	"\trule_type\x18\x01 \x01(\tR\bruleType\x12'\n" +
	"\x0fpenalty_minutes\x18\x02 \x01(\x05R\x0epenaltyMinutes\x12'\n" +
	"\x0fpenalty_formula\x18\x03 \x01(\tR\x0epenaltyFormula\x12.\n" +
	"\x13penalty_cap_minutes\x18\x04 \x01(\x05R\x11penaltyCapMinutes\x129\n" +
	"\x19freeze_minutes_before_end\x18\x05 \x01(\x05R\x16freezeMinutesBeforeEnd\x12\x1d\n" +
	"\n" +
	"allow_hack\x18\x06 \x01(\bR\tallowHack\x12\x1f\n" +
	"\vhack_reward\x18\a \x01(\x05R\n" +
	"hackReward\x12!\n" +
	"\fhack_penalty\x18\b \x01(\x05R\vhackPenalty\x12=\n" +
	"\x1bmax_submissions_per_problem\x18\t \x01(\x05R\x18maxSubmissionsPerProblem\x12\x1d\n" +
	"\n" +
	"score_mode\x18\n" +
	" \x01(\tR\tscoreMode\x12=\n" +
	"\x1bpublish_solutions_after_end\x18\v \x01(\bR\x18publishSolutionsAfterEnd\x12B\n" +
	"\x1dvirtual_participation_enabled\x18\f \x01(\bR\x1bvirtualParticipationEnabled\"3\n" +
	"\x12ContestMetaRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"\xbe\x01\n" +
	"\x13ContestMetaResponse\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\tR\x05endAt\x12(\n" +
	"\x04rule\x18\x06 \x01(\v2\x14.contest.ContestRuleR\x04rule\"3\n" +
	"\x12ContestRuleRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"?\n" +
	"\x13ContestRuleResponse\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.contest.ContestRuleR\x04rule\"\x8f\x01\n" +
	"\x0eContestProblem\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\avisible\x18\x04 \x01(\bR\avisible\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"7\n" +
	"\x16ContestProblemsRequest\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\"H\n" +
	"\x17ContestProblemsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.contest.ContestProblemR\x05items2\xde\x02\n" +
	"\n" +
	"ContestRpc\x12]\n" +
	"\x12CheckParticipation\x12\".contest.CheckParticipationRequest\x1a#.contest.CheckParticipationResponse\x12K\n" +
	"\x0eGetContestMeta\x12\x1b.contest.ContestMetaRequest\x1a\x1c.contest.ContestMetaResponse\x12K\n" +
	"\x0eGetContestRule\x12\x1b.contest.ContestRuleRequest\x1a\x1c.contest.ContestRuleResponse\x12W\n" +
	"\x12GetContestProblems\x12\x1f.contest.ContestProblemsRequest\x1a .contest.ContestProblemsResponseB!Z\x1ffuzoj/api/proto/contest;contestb\x06proto3"

var (
	file_contest_contest_proto_rawDescOnce sync.Once
	file_contest_contest_proto_rawDescData []byte
)

func file_contest_contest_proto_rawDescGZIP() []byte {
	file_contest_contest_proto_rawDescOnce.Do(func() {
		file_contest_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contest_contest_proto_rawDesc), len(file_contest_contest_proto_rawDesc)))
	})
	return file_contest_contest_proto_rawDescData
}

var file_contest_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_contest_contest_proto_goTypes = []any{
	(*CheckParticipationRequest)(nil),  // 0: contest.CheckParticipationRequest
	(*CheckParticipationResponse)(nil), // 1: contest.CheckParticipationResponse
	(*ContestRule)(nil),                // 2: contest.ContestRule
	(*ContestMetaRequest)(nil),         // 3: contest.ContestMetaRequest
	(*ContestMetaResponse)(nil),        // 4: contest.ContestMetaResponse
	(*ContestRuleRequest)(nil),         // 5: contest.ContestRuleRequest
	(*ContestRuleResponse)(nil),        // 6: contest.ContestRuleResponse
	(*ContestProblem)(nil),             // 7: contest.ContestProblem
	(*ContestProblemsRequest)(nil),     // 8: contest.ContestProblemsRequest
	(*ContestProblemsResponse)(nil),    // 9: contest.ContestProblemsResponse
}
var file_contest_contest_proto_depIdxs = []int32{
	2, // 0: contest.ContestMetaResponse.rule:type_name -> contest.ContestRule
	2, // 1: contest.ContestRuleResponse.rule:type_name -> contest.ContestRule
	7, // 2: contest.ContestProblemsResponse.items:type_name -> contest.ContestProblem
	0, // 3: contest.ContestRpc.CheckParticipation:input_type -> contest.CheckParticipationRequest
	3, // 4: contest.ContestRpc.GetContestMeta:input_type -> contest.ContestMetaRequest
	5, // 5: contest.ContestRpc.GetContestRule:input_type -> contest.ContestRuleRequest
	8, // 6: contest.ContestRpc.GetContestProblems:input_type -> contest.ContestProblemsRequest
	1, // 7: contest.ContestRpc.CheckParticipation:output_type -> contest.CheckParticipationResponse
	4, // 8: contest.ContestRpc.GetContestMeta:output_type -> contest.ContestMetaResponse
	6, // 9: contest.ContestRpc.GetContestRule:output_type -> contest.ContestRuleResponse
	9, // 10: contest.ContestRpc.GetContestProblems:output_type -> contest.ContestProblemsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contest_contest_proto_init() }
func file_contest_contest_proto_init() {
	if File_contest_contest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contest_contest_proto_rawDesc), len(file_contest_contest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contest_contest_proto_goTypes,
		DependencyIndexes: file_contest_contest_proto_depIdxs,
		MessageInfos:      file_contest_contest_proto_msgTypes,
	}.Build()
	File_contest_contest_proto = out.File
	file_contest_contest_proto_goTypes = nil
	file_contest_contest_proto_depIdxs = nil
}
