// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: contest/contest.proto

package contest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContestRpc_CheckParticipation_FullMethodName = "/contest.ContestRpc/CheckParticipation"
	ContestRpc_GetContestMeta_FullMethodName     = "/contest.ContestRpc/GetContestMeta"
	ContestRpc_GetContestRule_FullMethodName     = "/contest.ContestRpc/GetContestRule"
	ContestRpc_GetContestProblems_FullMethodName = "/contest.ContestRpc/GetContestProblems"
)

// ContestRpcClient is the client API for ContestRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContestRpcClient interface {
	CheckParticipation(ctx context.Context, in *CheckParticipationRequest, opts ...grpc.CallOption) (*CheckParticipationResponse, error)
	GetContestMeta(ctx context.Context, in *ContestMetaRequest, opts ...grpc.CallOption) (*ContestMetaResponse, error)
	GetContestRule(ctx context.Context, in *ContestRuleRequest, opts ...grpc.CallOption) (*ContestRuleResponse, error)
	GetContestProblems(ctx context.Context, in *ContestProblemsRequest, opts ...grpc.CallOption) (*ContestProblemsResponse, error)
}

type contestRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewContestRpcClient(cc grpc.ClientConnInterface) ContestRpcClient {
	return &contestRpcClient{cc}
}

func (c *contestRpcClient) CheckParticipation(ctx context.Context, in *CheckParticipationRequest, opts ...grpc.CallOption) (*CheckParticipationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckParticipationResponse)
	err := c.cc.Invoke(ctx, ContestRpc_CheckParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestRpcClient) GetContestMeta(ctx context.Context, in *ContestMetaRequest, opts ...grpc.CallOption) (*ContestMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContestMetaResponse)
	err := c.cc.Invoke(ctx, ContestRpc_GetContestMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestRpcClient) GetContestRule(ctx context.Context, in *ContestRuleRequest, opts ...grpc.CallOption) (*ContestRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContestRuleResponse)
	err := c.cc.Invoke(ctx, ContestRpc_GetContestRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contestRpcClient) GetContestProblems(ctx context.Context, in *ContestProblemsRequest, opts ...grpc.CallOption) (*ContestProblemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContestProblemsResponse)
	err := c.cc.Invoke(ctx, ContestRpc_GetContestProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContestRpcServer is the server API for ContestRpc service.
// All implementations must embed UnimplementedContestRpcServer
// for forward compatibility.
type ContestRpcServer interface {
	CheckParticipation(context.Context, *CheckParticipationRequest) (*CheckParticipationResponse, error)
	GetContestMeta(context.Context, *ContestMetaRequest) (*ContestMetaResponse, error)
	GetContestRule(context.Context, *ContestRuleRequest) (*ContestRuleResponse, error)
	GetContestProblems(context.Context, *ContestProblemsRequest) (*ContestProblemsResponse, error)
	mustEmbedUnimplementedContestRpcServer()
}

// UnimplementedContestRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContestRpcServer struct{}

func (UnimplementedContestRpcServer) CheckParticipation(context.Context, *CheckParticipationRequest) (*CheckParticipationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckParticipation not implemented")
}
func (UnimplementedContestRpcServer) GetContestMeta(context.Context, *ContestMetaRequest) (*ContestMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContestMeta not implemented")
}
func (UnimplementedContestRpcServer) GetContestRule(context.Context, *ContestRuleRequest) (*ContestRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContestRule not implemented")
}
func (UnimplementedContestRpcServer) GetContestProblems(context.Context, *ContestProblemsRequest) (*ContestProblemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContestProblems not implemented")
}
func (UnimplementedContestRpcServer) mustEmbedUnimplementedContestRpcServer() {}
func (UnimplementedContestRpcServer) testEmbeddedByValue()                    {}

// UnsafeContestRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContestRpcServer will
// result in compilation errors.
type UnsafeContestRpcServer interface {
	mustEmbedUnimplementedContestRpcServer()
}

func RegisterContestRpcServer(s grpc.ServiceRegistrar, srv ContestRpcServer) {
	// If the following call panics, it indicates UnimplementedContestRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContestRpc_ServiceDesc, srv)
}

func _ContestRpc_CheckParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckParticipationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestRpcServer).CheckParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestRpc_CheckParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestRpcServer).CheckParticipation(ctx, req.(*CheckParticipationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestRpc_GetContestMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContestMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestRpcServer).GetContestMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestRpc_GetContestMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestRpcServer).GetContestMeta(ctx, req.(*ContestMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestRpc_GetContestRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContestRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestRpcServer).GetContestRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestRpc_GetContestRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestRpcServer).GetContestRule(ctx, req.(*ContestRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContestRpc_GetContestProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContestProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContestRpcServer).GetContestProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContestRpc_GetContestProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContestRpcServer).GetContestProblems(ctx, req.(*ContestProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContestRpc_ServiceDesc is the grpc.ServiceDesc for ContestRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContestRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contest.ContestRpc",
	HandlerType: (*ContestRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckParticipation",
			Handler:    _ContestRpc_CheckParticipation_Handler,
		},
		{
			MethodName: "GetContestMeta",
			Handler:    _ContestRpc_GetContestMeta_Handler,
		},
		{
			MethodName: "GetContestRule",
			Handler:    _ContestRpc_GetContestRule_Handler,
		},
		{
			MethodName: "GetContestProblems",
			Handler:    _ContestRpc_GetContestProblems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contest/contest.proto",
}
