// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBansFieldNames          = builder.RawFieldNames(&UserBans{})
	userBansRows                = strings.Join(userBansFieldNames, ",")
	userBansRowsExpectAutoSet   = strings.Join(stringx.Remove(userBansFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userBansRowsWithPlaceHolder = strings.Join(stringx.Remove(userBansFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserBansIdPrefix = "cache:userBans:id:"
)

type (
	userBansModel interface {
		Insert(ctx context.Context, data *UserBans) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserBans, error)
		Update(ctx context.Context, data *UserBans) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserBansModel struct {
		sqlc.CachedConn
		table string
	}

	UserBans struct {
		Id           int64          `db:"id"`
		UserId       int64          `db:"user_id"`
		BanType      string         `db:"ban_type"`
		Reason       string         `db:"reason"`
		BannedBy     int64          `db:"banned_by"`
		StartTime    time.Time      `db:"start_time"`
		EndTime      sql.NullTime   `db:"end_time"`
		Status       string         `db:"status"`
		CancelReason sql.NullString `db:"cancel_reason"`
		CancelledBy  sql.NullInt64  `db:"cancelled_by"`
		CancelledAt  sql.NullTime   `db:"cancelled_at"`
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newUserBansModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserBansModel {
	return &defaultUserBansModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_bans`",
	}
}

func (m *defaultUserBansModel) Delete(ctx context.Context, id int64) error {
	userBansIdKey := fmt.Sprintf("%s%v", cacheUserBansIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userBansIdKey)
	return err
}

func (m *defaultUserBansModel) FindOne(ctx context.Context, id int64) (*UserBans, error) {
	userBansIdKey := fmt.Sprintf("%s%v", cacheUserBansIdPrefix, id)
	var resp UserBans
	err := m.QueryRowCtx(ctx, &resp, userBansIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBansRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBansModel) Insert(ctx context.Context, data *UserBans) (sql.Result, error) {
	userBansIdKey := fmt.Sprintf("%s%v", cacheUserBansIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userBansRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.BanType, data.Reason, data.BannedBy, data.StartTime, data.EndTime, data.Status, data.CancelReason, data.CancelledBy, data.CancelledAt)
	}, userBansIdKey)
	return ret, err
}

func (m *defaultUserBansModel) Update(ctx context.Context, data *UserBans) error {
	userBansIdKey := fmt.Sprintf("%s%v", cacheUserBansIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBansRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.BanType, data.Reason, data.BannedBy, data.StartTime, data.EndTime, data.Status, data.CancelReason, data.CancelledBy, data.CancelledAt, data.Id)
	}, userBansIdKey)
	return err
}

func (m *defaultUserBansModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserBansIdPrefix, primary)
}

func (m *defaultUserBansModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBansRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserBansModel) tableName() string {
	return m.table
}
