// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rank.proto

package rankrpc

import (
	"context"

	rankpb "fuzoj/api/proto/rank"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LeaderboardEntry      = rankpb.LeaderboardEntry
	LeaderboardReply      = rankpb.LeaderboardReply
	PageInfo              = rankpb.PageInfo
	GetLeaderboardRequest = rankpb.GetLeaderboardRequest
	GetMemberRankRequest  = rankpb.GetMemberRankRequest
	MemberRankReply       = rankpb.MemberRankReply

	RankRpc interface {
		GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardReply, error)
		GetMemberRank(ctx context.Context, in *GetMemberRankRequest, opts ...grpc.CallOption) (*MemberRankReply, error)
	}

	defaultRankRpc struct {
		cli zrpc.Client
	}
)

func NewRankRpc(cli zrpc.Client) RankRpc {
	return &defaultRankRpc{cli: cli}
}

func (m *defaultRankRpc) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardReply, error) {
	client := rankpb.NewRankRpcClient(m.cli.Conn())
	return client.GetLeaderboard(ctx, in, opts...)
}

func (m *defaultRankRpc) GetMemberRank(ctx context.Context, in *GetMemberRankRequest, opts ...grpc.CallOption) (*MemberRankReply, error) {
	client := rankpb.NewRankRpcClient(m.cli.Conn())
	return client.GetMemberRank(ctx, in, opts...)
}
