package db

import (
	"context"
	"database/sql"
	"time"
)

// Database defines the core interface for database operations.
// This abstraction allows switching between different database implementations
// (MySQL, PostgreSQL, etc.) without changing business logic.
type Database interface {
	// Query executes a query that returns rows
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)

	// QueryRow executes a query that returns at most one row
	QueryRow(ctx context.Context, query string, args ...interface{}) Row

	// Exec executes a query that doesn't return rows (INSERT, UPDATE, DELETE)
	Exec(ctx context.Context, query string, args ...interface{}) (Result, error)

	// Transaction executes a function within a database transaction
	Transaction(ctx context.Context, fn func(tx Transaction) error) error

	// BeginTx starts a new transaction with the given options
	BeginTx(ctx context.Context, opts *TxOptions) (Transaction, error)

	// Prepare creates a prepared statement for later queries or executions
	Prepare(ctx context.Context, query string) (Stmt, error)

	// Ping verifies a connection to the database is still alive
	Ping(ctx context.Context) error

	// Close closes the database connection
	Close() error

	// Stats returns database statistics
	Stats() Stats

	// GetDB returns the underlying database instance (use with caution)
	GetDB() interface{}
}

// Transaction defines the interface for database transaction operations
type Transaction interface {
	// Query executes a query within the transaction
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)

	// QueryRow executes a query that returns at most one row within the transaction
	QueryRow(ctx context.Context, query string, args ...interface{}) Row

	// Exec executes a query within the transaction
	Exec(ctx context.Context, query string, args ...interface{}) (Result, error)

	// Prepare creates a prepared statement within the transaction
	Prepare(ctx context.Context, query string) (Stmt, error)

	// Commit commits the transaction
	Commit() error

	// Rollback rolls back the transaction
	Rollback() error
}

// Rows is an abstraction of sql.Rows to avoid direct dependency
type Rows interface {
	// Next prepares the next result row
	Next() bool

	// Scan copies the columns from the current row into the values pointed at by dest
	Scan(dest ...interface{}) error

	// Close closes the Rows, preventing further enumeration
	Close() error

	// Err returns the error, if any, that was encountered during iteration
	Err() error

	// Columns returns the column names
	Columns() ([]string, error)

	// ColumnTypes returns column type information
	ColumnTypes() ([]ColumnType, error)

	// NextResultSet advances to the next result set
	NextResultSet() bool
}

// Row is an abstraction of sql.Row to avoid direct dependency
type Row interface {
	// Scan copies the columns from the matched row into the values pointed at by dest
	Scan(dest ...interface{}) error
}

// Result is an abstraction of sql.Result to avoid direct dependency
type Result interface {
	// LastInsertId returns the integer generated by the database in response to a command
	LastInsertId() (int64, error)

	// RowsAffected returns the number of rows affected by an update, insert, or delete
	RowsAffected() (int64, error)
}

// Stmt is an abstraction of sql.Stmt for prepared statements
type Stmt interface {
	// Exec executes a prepared statement with the given arguments
	Exec(ctx context.Context, args ...interface{}) (Result, error)

	// Query executes a prepared query statement with the given arguments
	Query(ctx context.Context, args ...interface{}) (Rows, error)

	// QueryRow executes a prepared query statement that returns at most one row
	QueryRow(ctx context.Context, args ...interface{}) Row

	// Close closes the statement
	Close() error
}

// ColumnType contains information about a column type
type ColumnType interface {
	// Name returns the column name
	Name() string

	// DatabaseTypeName returns the database system type name
	DatabaseTypeName() string

	// Length returns the column length (for variable length types)
	Length() (length int64, ok bool)

	// Nullable returns whether the column may be null
	Nullable() (nullable, ok bool)

	// DecimalSize returns the scale and precision of a decimal type
	DecimalSize() (precision, scale int64, ok bool)

	// ScanType returns a Go type suitable for scanning into
	ScanType() interface{}
}

// TxOptions holds the transaction options
type TxOptions struct {
	// Isolation is the transaction isolation level
	Isolation IsolationLevel

	// ReadOnly indicates whether the transaction is read-only
	ReadOnly bool
}

// IsolationLevel represents the transaction isolation level
type IsolationLevel int

const (
	// LevelDefault uses the default isolation level of the database
	LevelDefault IsolationLevel = iota

	// LevelReadUncommitted allows dirty reads
	LevelReadUncommitted

	// LevelReadCommitted prevents dirty reads
	LevelReadCommitted

	// LevelRepeatableRead prevents dirty and non-repeatable reads
	LevelRepeatableRead

	// LevelSerializable prevents dirty, non-repeatable reads and phantom reads
	LevelSerializable
)

// Stats represents database statistics
type Stats struct {
	MaxOpenConnections int           // Maximum number of open connections to the database
	OpenConnections    int           // The number of established connections
	InUse              int           // The number of connections currently in use
	Idle               int           // The number of idle connections
	WaitCount          int64         // The total number of connections waited for
	WaitDuration       time.Duration // The total time blocked waiting for a new connection
	MaxIdleClosed      int64         // The total number of connections closed due to SetMaxIdleConns
	MaxLifetimeClosed  int64         // The total number of connections closed due to SetConnMaxLifetime
}

// Scanner is the interface that wraps the Scan method for scanning database rows into structs
type Scanner interface {
	Scan(dest ...interface{}) error
}

// ConvertSQLStats converts sql.DBStats to our Stats type
func ConvertSQLStats(s sql.DBStats) Stats {
	return Stats{
		MaxOpenConnections: s.MaxOpenConnections,
		OpenConnections:    s.OpenConnections,
		InUse:              s.InUse,
		Idle:               s.Idle,
		WaitCount:          s.WaitCount,
		WaitDuration:       s.WaitDuration,
		MaxIdleClosed:      s.MaxIdleClosed,
		MaxLifetimeClosed:  s.MaxLifetimeClosed,
	}
}

// ConvertIsolationLevel converts our IsolationLevel to sql.IsolationLevel
func ConvertIsolationLevel(level IsolationLevel) sql.IsolationLevel {
	switch level {
	case LevelReadUncommitted:
		return sql.LevelReadUncommitted
	case LevelReadCommitted:
		return sql.LevelReadCommitted
	case LevelRepeatableRead:
		return sql.LevelRepeatableRead
	case LevelSerializable:
		return sql.LevelSerializable
	default:
		return sql.LevelDefault
	}
}

// ConvertTxOptions converts our TxOptions to sql.TxOptions
func ConvertTxOptions(opts *TxOptions) *sql.TxOptions {
	if opts == nil {
		return nil
	}
	return &sql.TxOptions{
		Isolation: ConvertIsolationLevel(opts.Isolation),
		ReadOnly:  opts.ReadOnly,
	}
}
