// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fuzoj/services/problem_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/data-pack/uploads/:upload_id/abort",
				Handler: AbortUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/data-pack/uploads/:upload_id/complete",
				Handler: CompleteUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/data-pack/uploads/:upload_id/sign",
				Handler: SignUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/data-pack/uploads:prepare",
				Handler: PrepareUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/latest",
				Handler: GetLatestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/versions/:version/publish",
				Handler: PublishVersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/problems"),
	)
}
