// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: contest.proto

package server

import (
	"context"

	contestpb "fuzoj/api/proto/contest"
	"fuzoj/services/contest_rpc_service/internal/logic"
	"fuzoj/services/contest_rpc_service/internal/svc"
)

type ContestRpcServer struct {
	svcCtx *svc.ServiceContext
	contestpb.UnimplementedContestRpcServer
}

func NewContestRpcServer(svcCtx *svc.ServiceContext) *ContestRpcServer {
	return &ContestRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ContestRpcServer) CheckParticipation(ctx context.Context, in *contestpb.CheckParticipationRequest) (*contestpb.CheckParticipationResponse, error) {
	l := logic.NewCheckParticipationLogic(ctx, s.svcCtx)
	return l.CheckParticipation(in)
}

func (s *ContestRpcServer) CheckSubmissionEligibility(ctx context.Context, in *contestpb.CheckSubmissionEligibilityRequest) (*contestpb.CheckSubmissionEligibilityResponse, error) {
	l := logic.NewCheckSubmissionEligibilityLogic(ctx, s.svcCtx)
	return l.CheckSubmissionEligibility(in)
}

func (s *ContestRpcServer) GetContestMeta(ctx context.Context, in *contestpb.ContestMetaRequest) (*contestpb.ContestMetaResponse, error) {
	l := logic.NewGetContestMetaLogic(ctx, s.svcCtx)
	return l.GetContestMeta(in)
}

func (s *ContestRpcServer) GetContestRule(ctx context.Context, in *contestpb.ContestRuleRequest) (*contestpb.ContestRuleResponse, error) {
	l := logic.NewGetContestRuleLogic(ctx, s.svcCtx)
	return l.GetContestRule(in)
}

func (s *ContestRpcServer) GetContestProblems(ctx context.Context, in *contestpb.ContestProblemsRequest) (*contestpb.ContestProblemsResponse, error) {
	l := logic.NewGetContestProblemsLogic(ctx, s.svcCtx)
	return l.GetContestProblems(in)
}
